#!/bin/sh /etc/rc.common

START=99
STOP=10

start() {
	/usr/lib/sshfirewall/sshfirewall.sh start
}

stop() {
	/usr/lib/sshfirewall/sshfirewall.sh stop
}

restart() {
	/usr/lib/sshfirewall/sshfirewall.sh restart
}

status() {
	/usr/lib/sshfirewall/sshfirewall.sh status
}
